### ISSUE TITLE
Helm install failure {"statusCode":400,"message":"Unexpected token k in JSON at position 132","error":"Bad Request"}

### ISSUE THREAD

**Issue by scott-dunt** [komodorio/Install#22]
Won't install on K8s V1.16.13 on Debian GNU/Linux 9 (stretch)
 
Added komodor chart repository successfully!                                                                                                                                                 
Installing Komodor, this might take a minute                                                                                                                                                 
Komodor install failed...                                                                                                                                                                    
Error: UPGRADE FAILED: timed out waiting for the condition                                                                                                                                   
{"statusCode":400,"message":"Unexpected token r in JSON at position 115","error":"Bad Request"}

(using another toolset....) I find that the watcher pod is not starting:

Error creating: pods "k8s-watcher-5557f7875c-" is forbidden: pods with system-cluster-critical priorityClass is not permitted in komodor namespace

Seems to be related to: https://bugzilla.redhat.com/show_bug.cgi?id=1636292

Suggestions?

**Comment by erez-rabih** [comment]
regarding the forbidden priority class, it seems that you have configured a resource quota that limits the creation of pods with `system-cluster-critical` priority class in new namespaces
see [this doc](https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default) for more information

to resolve this, you can edit the watcher deployment with the following command:
```
$> kubectl  -n komodor edit deployment k8s-watcher
```
remove the following configuration `priorityClassName: system-cluster-critical` and save the deployment

I would expect that to fix the issue

**Comment by scott-dunt** [comment]
That fixed it.. thanks for the quick response.. 

Sorry it took me a while to test it out and post an update.
